In [24]:
import numpy as np

In [32]:
x=[0,1.5,2.8,4.4,6.1,8.0]
y=[0.0,0.9,2.5,6.6,7.7,8.0]
n=len(x)-1
Dy=np.zeros((n+1,n+1))
print(Dy)
Dy[:,0]=y
for j in range(n):
    for i in range(j+1,n+1):
        Dy[i,j+1]= (Dy[i,j]-Dy[j,j])/(x[i]-x[j])
        
print('\n',Dy)
xp=float(input('Enter x:'))
yp=Dy[0,0]
for i in range(n):
    xprod=1
    for j in range(i+1):
        xprod *= xp-x[j]
    yp += xprod*Dy[i+1,i+1]
print("For x=%0.1f,y=%0.1f" % (xp,yp))
        

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

 [[ 0.          0.          0.          0.          0.          0.        ]
 [ 0.9         0.6         0.          0.          0.          0.        ]
 [ 2.5         0.89285714  0.22527473  0.          0.          0.        ]
 [ 6.6         1.5         0.31034483  0.05316881  0.          0.        ]
 [ 7.7         1.26229508  0.14397719 -0.02463562 -0.04576731  0.        ]
 [ 8.          1.          0.06153846 -0.03148774 -0.02351571  0.01171137]]


Enter x: 5


For x=5.0,y=7.6


In [34]:
import numpy as np

x = [0, 1.5, 2.8, 4.4, 6.1, 8.0]
y = [0.0, 0.9, 2.5, 6.6, 7.7, 8.0]
n = len(x) - 1
Dy = np.zeros((n + 1, n + 1))
print(Dy)

Dy[:, 0] = y
for j in range(n):
    for i in range(j + 1, n + 1):
        Dy[i, j + 1] = (Dy[i, j] - Dy[j, j]) / (x[i] - x[j])

print('\n', Dy)

xp = float(input('Enter x: '))
yp = Dy[0, 0]
for i in range(n):
    xprod = 1
    for j in range(i + 1):
        xprod *= xp - x[j]
    yp += xprod * Dy[i + 1, i + 1]

print("For x = %.1f, y = %.1f" % (xp, yp))


[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

 [[ 0.          0.          0.          0.          0.          0.        ]
 [ 0.9         0.6         0.          0.          0.          0.        ]
 [ 2.5         0.89285714  0.22527473  0.          0.          0.        ]
 [ 6.6         1.5         0.31034483  0.05316881  0.          0.        ]
 [ 7.7         1.26229508  0.14397719 -0.02463562 -0.04576731  0.        ]
 [ 8.          1.          0.06153846 -0.03148774 -0.02351571  0.01171137]]


Enter x:  1.5


For x = 1.5, y = 0.9
