In [92]:
#interpolation_scipy
x = [0, 20, 40, 60, 80, 100]
y = [26.0, 48.6, 61.6, 71.2, 74.8, 75.2]

In [94]:
from scipy.interpolate import interp1d,lagrange

In [63]:
f=interp1d(x,y)  #Linear interpolation
f(0)

array(26.)

In [65]:
print(f(0))

26.0


In [67]:
print(f(10))

37.3


In [69]:
f=interp1d(x,y,'quadratic')

In [71]:
print(f(70))
print(f(50))

73.6202205882353
66.95208333333333


In [73]:
f=interp1d(x,y,'cubic')

In [75]:
print(f(70))
print(f(50))

73.70166666666667
66.945


In [77]:
print(f(70))
print(f(50))

73.70166666666667
66.945


In [79]:
print(f(19))

47.77203666666668


In [82]:
L=lagrange(x,y)

In [86]:
print(L)

           5             4             3           2
3.698e-08 x - 9.688e-06 x + 0.0009219 x - 0.04463 x + 1.725 x + 26


In [88]:
print(L(50))

66.94765624999957


In [90]:
print(L(40))

61.599999999999746


In [96]:
#Curve fittinhg in Scipy

In [98]:
x = [0, 20, 40, 60, 80, 100]
y = [26.0, 48.6, 61.6, 71.2, 74.8, 75.2]

In [100]:
from scipy.stats import linregress

In [102]:
L=linregress(x,y)

In [104]:
print(L)

LinregressResult(slope=0.47742857142857137, intercept=35.695238095238096, rvalue=0.9254673464560844, pvalue=0.008125655881776562, stderr=0.09771442495116786, intercept_stderr=5.916902266076723)


In [106]:
print(L.slope)

0.47742857142857137


In [108]:
print(L.intercept)

35.695238095238096


In [110]:
x=[0,1,2,3,4,5]
y=[2,8,14,28,62]

In [122]:
from scipy.optimize import curve_fit

In [130]:
from scipy.optimize import curve_fit
import numpy as np

# Define the quadratic function
def f(x, a0, a1, a2):
    return a0 + a1 * x + a2 * x**2

# Given data points
x = np.array([0, 1, 2, 3, 4, 5])
y = np.array([2, 8, 14, 28, 39, 62])

# Use curve_fit to find the best-fit parameters a0, a1, and a2
a, b = curve_fit(f, x, y)

# Print the resulting coefficients
print(a)


[2.67857143 2.25357143 1.875     ]


In [134]:
def f(x, a0, a1, a2,a3):
    return a0 + a1 * x + a2 * x**2 +a3 * x**3

# Given data points
x = np.array([0, 1, 2, 3, 4, 5])
y = np.array([2, 8, 14, 28, 39, 62])

# Use curve_fit to find the best-fit parameters a0, a1, and a2
a, b = curve_fit(f, x, y)

# Print the resulting coefficients
print(a)
print(b)

[ 1.92857143e+00  5.67857143e+00 -2.17847962e-12  2.50000000e-01]
[[ 3.68225352e+00 -1.81170252e+00 -7.83525133e-06  4.62383516e-02]
 [-1.81170252e+00  1.75673872e+00 -2.18158095e-05 -6.34981147e-02]
 [-7.83525133e-06 -2.18158095e-05  2.41729418e-09  1.07542719e-06]
 [ 4.62383516e-02 -6.34981147e-02  1.07542719e-06  2.73863476e-03]]
