In [65]:
import numpy as np

# Define the matrix with 5 rows and 4 columns
A = np.array([
    [3, -2, 5, 0,2],
    [4, 5, 8, 1,4],
    [1, 1, 2, 1,5],
    [2, 7, 6, 5,7]
])

# Print the matrix
print(A)

# Print the order of the matrix
print(f"Order of matrix: {A.shape}")


[[ 3 -2  5  0  2]
 [ 4  5  8  1  4]
 [ 1  1  2  1  5]
 [ 2  7  6  5  7]]
Order of matrix: (4, 5)


In [133]:
import numpy as np

# Define the matrix
A = np.array([
    [3, -2, 5, 0, 2],
    [4, 5, 8, 1, 4],
    [1, 1, 2, 1, 5],
    [2, 7, 6, 5, 7]
], dtype=float)  # Ensure matrix is of type float

print("Original Matrix A:\n", A)

# Compute the factors
factor_2 = A[0, 0] / A[1, 0]  # Factor for row 2
factor_3 = A[0, 0] / A[2, 0]  # Factor for row 3
factor_4 = A[0, 0] / A[3, 0]  # Factor for row 4

# Multiply specific rows
A[1, :] *= factor_2  # Multiply 2nd row (index 1) by factor_2
A[2, :] *= factor_3  # Multiply 3rd row (index 2) by factor_3
A[3, :] *= factor_4  # Multiply 4th row (index 3) by factor_4

print("\nMatrix after row multiplications:\n", A)

# Perform the subtraction and update rows
# Subtract rows 2, 3, and 4 from row 1
A[1, :] = A[0, :] - A[1, :]  # Update row 2
A[2, :] = A[0, :] - A[2, :]  # Update row 3
A[3, :] = A[0, :] - A[3, :]  # Update row 4

print("\nMatrix after subtracting rows 2, 3, and 4 from row 1 and updating rows:\n", A)

# Compute the new factors for rows 3 and 4
factor_3_new = A[1, 1] / A[2, 1]  # Factor for row 3
factor_4_new = A[1, 1] / A[3, 1]  # Factor for row 4

print("\nMatrix before updating rows 3 and 4 with new factors:\n", A)

# Multiply rows 3 and 4 by the new factors
A[2, :] *= factor_3_new  # Multiply 3rd row (index 2) by factor_3_new
A[3, :] *= factor_4_new  # Multiply 4th row (index 3) by factor_4_new

# Perform the subtraction and update rows
# Subtract rows 2 and 3 from row 1
A[2, :] = A[1, :] - A[2, :]  # Update row 3
A[3, :] = A[1, :] - A[3, :]  # Update row 4

print("\nMatrix after updating rows 3 and 4 with new factors and subtracting from row 1:\n", A)

# Compute the new factor for row 4
factor_4_new = A[2, 2] / A[3, 2]  # Factor for row 4

# Multiply row 4 by the new factor
A[3, :] *= factor_4_new  # Multiply 4th row (index 3) by factor_4_new

# Perform the final update
# Subtract rows 2 and 3 from row 1
A[3, :] = A[2, :] - A[3, :]  # Update row 4

print("\nMatrix after final updates:\n", A)


Original Matrix A:
 [[ 3. -2.  5.  0.  2.]
 [ 4.  5.  8.  1.  4.]
 [ 1.  1.  2.  1.  5.]
 [ 2.  7.  6.  5.  7.]]

Matrix after row multiplications:
 [[ 3.   -2.    5.    0.    2.  ]
 [ 3.    3.75  6.    0.75  3.  ]
 [ 3.    3.    6.    3.   15.  ]
 [ 3.   10.5   9.    7.5  10.5 ]]

Matrix after subtracting rows 2, 3, and 4 from row 1 and updating rows:
 [[  3.    -2.     5.     0.     2.  ]
 [  0.    -5.75  -1.    -0.75  -1.  ]
 [  0.    -5.    -1.    -3.   -13.  ]
 [  0.   -12.5   -4.    -7.5   -8.5 ]]

Matrix before updating rows 3 and 4 with new factors:
 [[  3.    -2.     5.     0.     2.  ]
 [  0.    -5.75  -1.    -0.75  -1.  ]
 [  0.    -5.    -1.    -3.   -13.  ]
 [  0.   -12.5   -4.    -7.5   -8.5 ]]

Matrix after updating rows 3 and 4 with new factors and subtracting from row 1:
 [[ 3.   -2.    5.    0.    2.  ]
 [ 0.   -5.75 -1.   -0.75 -1.  ]
 [ 0.    0.    0.15  2.7  13.95]
 [ 0.    0.    0.84  2.7   2.91]]

Matrix after final updates:
 [[ 3.         -2.          5.        