In [161]:
import numpy as np

# Define the coefficient matrix A and the constants vector b
A = np.array([
    [2, 7, -1, 3, 1],
    [2, 3, 4, 1, 7],
    [6, 2, -3, 2, -1],
    [2, 1, 2, -1, 2],
    [3, 4, 1, -2, 1]
], dtype=float)

b = np.array([5, 7, 2, 3, 4], dtype=float)

# Initialize augmented matrix manually
n = len(b)
Aug = np.zeros((n, n+1))
Aug[:, :-1] = A
Aug[:, -1] = b

def print_matrix(matrix, step):
    """
    Print the current state of the matrix with a step description.
    """
    print(f"\n{step}:")
    print(matrix)
    print()

# Print initial augmented matrix
print_matrix(Aug, "Initial Augmented Matrix")

# Forward Elimination
for i in range(n):
    # Find the maximum element in the current column for pivoting
    max_row = i
    for k in range(i+1, n):
        if abs(Aug[k, i]) > abs(Aug[max_row, i]):
            max_row = k
    
    # Swap the current row with the row containing the maximum element
    if max_row != i:
        Aug[[i, max_row]] = Aug[[max_row, i]]
    
    # Print matrix after row swap
    print_matrix(Aug, f"After swapping row {i} with row {max_row}")
    
    # Normalize the pivot row
    Aug[i] = Aug[i] / Aug[i, i]
    
    # Print matrix after normalization of pivot row
    print_matrix(Aug, f"After normalizing pivot row {i}")
    
    # Eliminate all rows below the pivot row
    for j in range(i + 1, n):
        Aug[j] = Aug[j] - Aug[j, i] * Aug[i]
    
    # Print matrix after elimination
    print_matrix(Aug, f"After eliminating rows below pivot row {i}")

# Back Substitution
x = np.zeros(n)
for i in range(n - 1, -1, -1):
    x[i] = Aug[i, -1] - np.sum(Aug[i, i + 1:n] * x[i + 1:])

print("Final Solution:")
print(x)



Initial Augmented Matrix:
[[ 2.  7. -1.  3.  1.  5.]
 [ 2.  3.  4.  1.  7.  7.]
 [ 6.  2. -3.  2. -1.  2.]
 [ 2.  1.  2. -1.  2.  3.]
 [ 3.  4.  1. -2.  1.  4.]]


After swapping row 0 with row 2:
[[ 6.  2. -3.  2. -1.  2.]
 [ 2.  3.  4.  1.  7.  7.]
 [ 2.  7. -1.  3.  1.  5.]
 [ 2.  1.  2. -1.  2.  3.]
 [ 3.  4.  1. -2.  1.  4.]]


After normalizing pivot row 0:
[[ 1.          0.33333333 -0.5         0.33333333 -0.16666667  0.33333333]
 [ 2.          3.          4.          1.          7.          7.        ]
 [ 2.          7.         -1.          3.          1.          5.        ]
 [ 2.          1.          2.         -1.          2.          3.        ]
 [ 3.          4.          1.         -2.          1.          4.        ]]


After eliminating rows below pivot row 0:
[[ 1.          0.33333333 -0.5         0.33333333 -0.16666667  0.33333333]
 [ 0.          2.33333333  5.          0.33333333  7.33333333  6.33333333]
 [ 0.          6.33333333  0.          2.33333333  1.33333333  

In [167]:
from scipy.linalg import solve, inv
A = np.array([
    [2, 7, -1, 3, 1],
    [2, 3, 4, 1, 7],
    [6, 2, -3, 2, -1],
    [2, 1, 2, -1, 2],
    [3, 4, 1, -2, 1]
], dtype=float)

B = np.array([5, 7, 2, 3, 4], dtype=float)

x=solve(A,B)
x

array([0.44444444, 0.55555556, 0.66666667, 0.22222222, 0.22222222])

In [171]:
x=np.dot(inv(A),B)
x

array([0.44444444, 0.55555556, 0.66666667, 0.22222222, 0.22222222])

In [175]:
x=np.linalg.solve(A,B)
x

array([0.44444444, 0.55555556, 0.66666667, 0.22222222, 0.22222222])